### ISSUE TITLE
OMDB requires API key

### ISSUE THREAD

**Issue by henno** [Jleagle/omdb-imdb-api-client#1]
OMDB requires API key now. My hack:

```
 try
    {
      $response = Curl::get('http://www.omdbapi.com/?apikey=xxxxxxxx', $params)
        ->run()->getJson();
    }
```

**Comment by Jleagle** [comment]
Hey, could you try pulling dev-master and setting your API key with:

`Imdb::setApiKey('xxx');`

I do not have an API key to test it with.
