### ISSUE TITLE
is the recent changes available via composer

### ISSUE THREAD

**Issue by thmohd** [Jleagle/omdb-imdb-api-client#2]
Thank you for this nice work. I had an issue with the ApiKey and I just noticed you fixed that. I installed the library using composer and it still brings the old code. is there a way I can use composer to fetch the recent code?

Thank you

**Comment by Jleagle** [comment]
The api key fix is not under a version yet (still waiting for it to be tested as i do not have an api key), you can get it by using:

```
  "require": {
    "jleagle/omdb-imdb-api-client": "dev-master"
  },
```

**Comment by thmohd** [comment]
Thanks man, works perfectly.

**Comment by Jleagle** [comment]
Good to know, thanks.
